Solved hw-3
nkhamm-spb/ml_hse pull request #3
Opened 2024-03-05 18:01 UTC by nkhamm-spb

2024-03-05 20:53 UTC, nkhamm-spb commented
print("Naive bayes:")
y_pred = clf.predict(x_test)
calc_metrics(y_test, y_pred)

забыл добавить

2024-03-09 11:54 UTC, svkov requested changes
Ставлю 0.4, поправь замечания

2024-03-09 11:54 UTC, svkov commented on notebooks/hw-3.ipynb
> +    "Хуже всего угадывается знак под номером 29, из картинки видно, что это предупреждение о движении велосипедов"
Какой вывод из этого можно сделать?

Нам интересно смотреть какие два класса между собой модель чаще всего путает, а не класс с самой низкой метрикой. Скорее всего, этого знака в датасете просто меньше, чем нужно, поэтому метрики низкие.

Надо пересчитать

2024-03-09 11:54 UTC, svkov commented on notebooks/hw-3.ipynb
> +    "Видно, что хуже всего работает SVC c полиномиальным ядром, про него мы знаем, что он менее точен зачастую, чем остальные ядра, и knn, так как он являеется самым наивным алгоритмом, и Евклидово р
Обучи НБК, там самое интересное

Можно не перезапускать все, только выводы поправь

2024-03-16 12:53 UTC, svkov commented
Зачтено

2024-03-16 12:53 UTC, svkov approved these changes

2024-03-16 18:33 UTC, merged